/**
 * Area registry for Kuwait real estate areas
 * Used for area-based filtering and display
 */
export interface Area {
  id: string
  en: string
  ar: string
  center: { lat: number; lng: number }
}

export const AREAS: Record<string, Area> = {
  // Capital Governorate
  rawda: {
    id: "rawda",
    en: "Rawda",
    ar: "الروضة",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  mansouriya: {
    id: "mansouriya",
    en: "Mansouriya",
    ar: "المنصورية",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  kaifan: {
    id: "kaifan",
    en: "Kaifan",
    ar: "كيفان",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  mirqab: {
    id: "mirqab",
    en: "Mirqab",
    ar: "المرقاب",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  adailiya: {
    id: "adailiya",
    en: "Adailiya",
    ar: "العديلية",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  nuzha: {
    id: "nuzha",
    en: "Nuzha",
    ar: "النزهة",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  qibla: {
    id: "qibla",
    en: "Qibla",
    ar: "القبلة",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  dasman: {
    id: "dasman",
    en: "Dasman",
    ar: "دسمان",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  khaldiya: {
    id: "khaldiya",
    en: "Khaldiya",
    ar: "الخالدية",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  faiha: {
    id: "faiha",
    en: "Faiha",
    ar: "الفيحاء",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  dasma: {
    id: "dasma",
    en: "Dasma",
    ar: "الدسمة",
    center: { lat: 29.3500, lng: 48.0167 },
  },
  salhiya: {
    id: "salhiya",
    en: "Salhiya",
    ar: "الصالحية",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  sharq: {
    id: "sharq",
    en: "Sharq",
    ar: "الشرق",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  qadsiya: {
    id: "qadsiya",
    en: "Qadsiya",
    ar: "القادسية",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  shamiya: {
    id: "shamiya",
    en: "Shamiya",
    ar: "الشامية",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  daiya: {
    id: "daiya",
    en: "Daiya",
    ar: "الدعية",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  yarmouk: {
    id: "yarmouk",
    en: "Yarmouk",
    ar: "اليرموك",
    center: { lat: 29.3052, lng: 48.0317 },
  },
  surra: {
    id: "surra",
    en: "Surra",
    ar: "السرة",
    center: { lat: 29.3000, lng: 48.0000 },
  },
  qortuba: {
    id: "qortuba",
    en: "Qortuba",
    ar: "قرطبة",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  qairawan: {
    id: "qairawan",
    en: "Qairawan",
    ar: "القيروان",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  nahdha: {
    id: "nahdha",
    en: "Nahdha",
    ar: "النهضة",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  granada: {
    id: "granada",
    en: "Granada",
    ar: "غرناطة",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  abdullahAlSalem: {
    id: "abdullahAlSalem",
    en: "Salem-Al Abdullah",
    ar: "ضاحية عبدالله السالم",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  bneidAlGar: {
    id: "bneidAlGar",
    en: "Bnaid Al-Qar",
    ar: "بنيد القار",
    center: { lat: 29.3600, lng: 48.0200 },
  },
  sulaibikhatWestNorth: {
    id: "sulaibikhatWestNorth",
    en: "Sulaibikhat West North",
    ar: "شمال غرب الصليبيخات",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  sulaibikhat: {
    id: "sulaibikhat",
    en: "Sulaibikhat",
    ar: "الصليبيخات",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  doha: {
    id: "doha",
    en: "Doha",
    ar: "الدوحة",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  shuwaikh: {
    id: "shuwaikh",
    en: "Shuwaikh",
    ar: "الشويخ",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  watya: {
    id: "watya",
    en: "Watya",
    ar: "الوطية",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  kuwaitCity: {
    id: "kuwaitCity",
    en: "Kuwait City",
    ar: "مدينة الكويت",
    center: { lat: 29.3759, lng: 47.9774 },
  },
  // Hawalli Governorate
  jabriya: {
    id: "jabriya",
    en: "Jabriya",
    ar: "الجابرية",
    center: { lat: 29.3167, lng: 48.0500 },
  },
  rumaithiya: {
    id: "rumaithiya",
    en: "Rumaithiya",
    ar: "الرميثية",
    center: { lat: 29.332, lng: 48.028 },
  },
  salmiya: {
    id: "salmiya",
    en: "Salmiya",
    ar: "السالمية",
    center: { lat: 29.3375, lng: 48.0758 },
  },
  shaab: {
    id: "shaab",
    en: "Shaab",
    ar: "الشعب",
    center: { lat: 29.332, lng: 48.028 },
  },
  hawalli: {
    id: "hawalli",
    en: "Hawalli",
    ar: "حولي",
    center: { lat: 29.3333, lng: 48.0833 },
  },
  hawalliMaidan: {
    id: "hawalliMaidan",
    en: "Hawalli Maidan",
    ar: "ميدان حولي",
    center: { lat: 29.332, lng: 48.028 },
  },
  nigra: {
    id: "nigra",
    en: "Nigra",
    ar: "النقرة",
    center: { lat: 29.332, lng: 48.028 },
  },
  bidaa: {
    id: "bidaa",
    en: "Bidaa",
    ar: "البدع",
    center: { lat: 29.332, lng: 48.028 },
  },
  bayan: {
    id: "bayan",
    en: "Bayan",
    ar: "بيان",
    center: { lat: 29.332, lng: 48.028 },
  },
  mishref: {
    id: "mishref",
    en: "Mishref",
    ar: "مشرف",
    center: { lat: 29.332, lng: 48.028 },
  },
  siddeeq: {
    id: "siddeeq",
    en: "Al-Siddiq",
    ar: "الصديق",
    center: { lat: 29.332, lng: 48.028 },
  },
  zahra: {
    id: "zahra",
    en: "Zahra",
    ar: "الزهراء",
    center: { lat: 29.332, lng: 48.028 },
  },
  hittin: {
    id: "hittin",
    en: "Hittin",
    ar: "حطين",
    center: { lat: 29.332, lng: 48.028 },
  },
  surraSouth: {
    id: "surraSouth",
    en: "Surra South",
    ar: "جنوب السرة",
    center: { lat: 29.332, lng: 48.028 },
  },
  salwa: {
    id: "salwa",
    en: "Salwa",
    ar: "سلوى",
    center: { lat: 29.2833, lng: 48.0833 },
  },
  shuhada: {
    id: "shuhada",
    en: "Shuhada",
    ar: "الشهداء",
    center: { lat: 29.332, lng: 48.028 },
  },
  salam: {
    id: "salam",
    en: "Salam",
    ar: "السالم",
    center: { lat: 29.332, lng: 48.028 },
  },
  abdullahAlMubarakHawalli: {
    id: "abdullahAlMubarakHawalli",
    en: "Abdullah-Al Mubarak",
    ar: "الجابر ضاحية مبارك العبدالله",
    center: { lat: 29.332, lng: 48.028 },
  },
  // Farwaniya Governorate
  khaitan: {
    id: "khaitan",
    en: "Khaitan",
    ar: "خيطان",
    center: { lat: 29.277, lng: 47.958 },
  },
  khaitanNew: {
    id: "khaitanNew",
    en: "Khaitan New",
    ar: "خيطان الجديدة",
    center: { lat: 29.277, lng: 47.958 },
  },
  jleebAlShuyoukh: {
    id: "jleebAlShuyoukh",
    en: "Jleeb Al-Shuyoukh",
    ar: "جليب الشيوخ",
    center: { lat: 29.277, lng: 47.958 },
  },
  ishbiliya: {
    id: "ishbiliya",
    en: "Ishbiliya",
    ar: "إشبيلية",
    center: { lat: 29.277, lng: 47.958 },
  },
  andalus: {
    id: "andalus",
    en: "Andalus",
    ar: "الأندلس",
    center: { lat: 29.277, lng: 47.958 },
  },
  khaitanAbrag: {
    id: "khaitanAbrag",
    en: "Khaitan Abrag",
    ar: "أبرق خيطان",
    center: { lat: 29.277, lng: 47.958 },
  },
  ardhiya: {
    id: "ardhiya",
    en: "Ardiya",
    ar: "العارضية",
    center: { lat: 29.277, lng: 47.958 },
  },
  omariya: {
    id: "omariya",
    en: "Omariya",
    ar: "العمرية",
    center: { lat: 29.277, lng: 47.958 },
  },
  farwaniya: {
    id: "farwaniya",
    en: "Farwaniya",
    ar: "الفروانية",
    center: { lat: 29.277, lng: 47.958 },
  },
  firdous: {
    id: "firdous",
    en: "Firdous",
    ar: "الفردوس",
    center: { lat: 29.277, lng: 47.958 },
  },
  abbasiya: {
    id: "abbasiya",
    en: "Abbasiya",
    ar: "العباسية",
    center: { lat: 29.277, lng: 47.958 },
  },
  sabahAlNasser: {
    id: "sabahAlNasser",
    en: "Sabah Al-Nasser",
    ar: "ضاحية صباح الناصر",
    center: { lat: 29.277, lng: 47.958 },
  },
  riggai: {
    id: "riggai",
    en: "Riggai",
    ar: "الرقعي",
    center: { lat: 29.277, lng: 47.958 },
  },
  rehab: {
    id: "rehab",
    en: "Rehab",
    ar: "الرحاب",
    center: { lat: 29.277, lng: 47.958 },
  },
  rabiya: {
    id: "rabiya",
    en: "Rabiya",
    ar: "الرابية",
    center: { lat: 29.277, lng: 47.958 },
  },
  mubarakAlAbdullah: {
    id: "mubarakAlAbdullah",
    en: "Mubarak-Al Abdullah",
    ar: "ضاحية عبدالله المبارك",
    center: { lat: 29.277, lng: 47.958 },
  },
  mubarakAlAbdullahWest: {
    id: "mubarakAlAbdullahWest",
    en: "Mubarak-Al Abdullah West",
    ar: "غرب عبدالله المبارك",
    center: { lat: 29.277, lng: 47.958 },
  },
  shaddadiya: {
    id: "shaddadiya",
    en: "Shaddadiya",
    ar: "الشدادية",
    center: { lat: 29.277, lng: 47.958 },
  },
  hassawi: {
    id: "hassawi",
    en: "Hassawi",
    ar: "الحساوي",
    center: { lat: 29.277, lng: 47.958 },
  },
  dajeej: {
    id: "dajeej",
    en: "Dajeej",
    ar: "الضجيج",
    center: { lat: 29.277, lng: 47.958 },
  },
  // Ahmadi Governorate
  mahboula: {
    id: "mahboula",
    en: "Mahboula",
    ar: "المهبولة",
    center: { lat: 29.076, lng: 48.082 },
  },
  dhaher: {
    id: "dhaher",
    en: "Dhaher",
    ar: "الظهر",
    center: { lat: 29.076, lng: 48.082 },
  },
  eqaila: {
    id: "eqaila",
    en: "Eqaila",
    ar: "العقيلة",
    center: { lat: 29.076, lng: 48.082 },
  },
  fintas: {
    id: "fintas",
    en: "Fintas",
    ar: "الفنطاس",
    center: { lat: 29.2500, lng: 48.1000 },
  },
  mangaf: {
    id: "mangaf",
    en: "Mangaf",
    ar: "المنقف",
    center: { lat: 29.076, lng: 48.082 },
  },
  sabahiya: {
    id: "sabahiya",
    en: "Sabahiya",
    ar: "الصباحية",
    center: { lat: 29.076, lng: 48.082 },
  },
  abuHalifa: {
    id: "abuHalifa",
    en: "Abu Halifa",
    ar: "أبو حليفة",
    center: { lat: 29.076, lng: 48.082 },
  },
  hadiya: {
    id: "hadiya",
    en: "Hadiya",
    ar: "هدية",
    center: { lat: 29.076, lng: 48.082 },
  },
  riqqa: {
    id: "riqqa",
    en: "Riqqa",
    ar: "الرقة",
    center: { lat: 29.076, lng: 48.082 },
  },
  ahmadi: {
    id: "ahmadi",
    en: "Ahmadi",
    ar: "الأحمدي",
    center: { lat: 29.076, lng: 48.082 },
  },
  fahaheel: {
    id: "fahaheel",
    en: "Fahaheel",
    ar: "الفحيحيل",
    center: { lat: 29.076, lng: 48.082 },
  },
  fahadAlAhmad: {
    id: "fahadAlAhmad",
    en: "Fahad Al-Ahmad",
    ar: "ضاحية فهد الأحمد",
    center: { lat: 29.076, lng: 48.082 },
  },
  jaberAlAli: {
    id: "jaberAlAli",
    en: "Jaber Al-Ali",
    ar: "ضاحية جابر العلي",
    center: { lat: 29.076, lng: 48.082 },
  },
  aliSabahAlSalemUmmAlHayman: {
    id: "aliSabahAlSalemUmmAlHayman",
    en: "Ali Sabah Al-Salem (Umm Al-Hayman)",
    ar: "ضاحية علي صباح السالم (أم الهيمان)",
    center: { lat: 29.076, lng: 48.082 },
  },
  sabahAlAhmadCity: {
    id: "sabahAlAhmadCity",
    en: "Sabah Al-Ahmad City",
    ar: "مدينة صباح الأحمد",
    center: { lat: 29.076, lng: 48.082 },
  },
  ahmadiEast: {
    id: "ahmadiEast",
    en: "Ahmadi East",
    ar: "شرق الأحمدي",
    center: { lat: 29.076, lng: 48.082 },
  },
  khiran: {
    id: "khiran",
    en: "Khiran",
    ar: "الخيران",
    center: { lat: 29.076, lng: 48.082 },
  },
  khiranCity: {
    id: "khiranCity",
    en: "Khiran City",
    ar: "مدينة الخيران",
    center: { lat: 29.076, lng: 48.082 },
  },
  sabahAlAhmadSeaCity: {
    id: "sabahAlAhmadSeaCity",
    en: "Sabah Al-Ahmad Sea City",
    ar: "مدينة صباح الأحمد البحرية",
    center: { lat: 29.076, lng: 48.082 },
  },
  zour: {
    id: "zour",
    en: "Zour",
    ar: "الزور",
    center: { lat: 29.076, lng: 48.082 },
  },
  bnaider: {
    id: "bnaider",
    en: "Bnaider",
    ar: "بنيدر",
    center: { lat: 29.076, lng: 48.082 },
  },
  julaia: {
    id: "julaia",
    en: "Julai'a",
    ar: "الجليعة",
    center: { lat: 29.076, lng: 48.082 },
  },
  nuwaiseeb: {
    id: "nuwaiseeb",
    en: "Nuwaiseeb",
    ar: "النويصيب",
    center: { lat: 29.076, lng: 48.082 },
  },
  shuaiba: {
    id: "shuaiba",
    en: "Shuaiba",
    ar: "الشعيبة",
    center: { lat: 29.076, lng: 48.082 },
  },
  minaAbdullah: {
    id: "minaAbdullah",
    en: "Abdullah Mina",
    ar: "ميناء عبدالله",
    center: { lat: 29.076, lng: 48.082 },
  },
  minaAlAhmadi: {
    id: "minaAlAhmadi",
    en: "Mina Al-Ahmadi",
    ar: "ميناء الأحمدي",
    center: { lat: 29.076, lng: 48.082 },
  },
  wafra: {
    id: "wafra",
    en: "Wafra",
    ar: "الوفرة",
    center: { lat: 29.076, lng: 48.082 },
  },
  // Mubarak Al-Kabeer Governorate
  messila: {
    id: "messila",
    en: "Messila",
    ar: "المسيلة",
    center: { lat: 29.3200, lng: 48.0400 },
  },
  abuAlHasaniya: {
    id: "abuAlHasaniya",
    en: "Abu Al-Hasaniya",
    ar: "أبو الحصاني",
    center: { lat: 29.191, lng: 48.070 },
  },
  qurain: {
    id: "qurain",
    en: "Qurain",
    ar: "القرين",
    center: { lat: 29.191, lng: 48.070 },
  },
  qusour: {
    id: "qusour",
    en: "Qusour",
    ar: "القصور",
    center: { lat: 29.191, lng: 48.070 },
  },
  adan: {
    id: "adan",
    en: "Adan",
    ar: "العدان",
    center: { lat: 29.191, lng: 48.070 },
  },
  masayel: {
    id: "masayel",
    en: "Masayel",
    ar: "المسايل",
    center: { lat: 29.191, lng: 48.070 },
  },
  fnaitees: {
    id: "fnaitees",
    en: "Fnaitees",
    ar: "الفنيطيس",
    center: { lat: 29.191, lng: 48.070 },
  },
  subhan: {
    id: "subhan",
    en: "Subhan",
    ar: "صبحان",
    center: { lat: 29.191, lng: 48.070 },
  },
  abuFtaira: {
    id: "abuFtaira",
    en: "Abu Ftaira",
    ar: "أبو فطيرة",
    center: { lat: 29.191, lng: 48.070 },
  },
  sabahAlSalem: {
    id: "sabahAlSalem",
    en: "Sabah Al-Salem",
    ar: "ضاحية صباح السالم",
    center: { lat: 29.191, lng: 48.070 },
  },
  mubarakAlKabeer: {
    id: "mubarakAlKabeer",
    en: "Mubarak Al-Kabeer",
    ar: "ضاحية مبارك الكبير",
    center: { lat: 29.191, lng: 48.070 },
  },
  // Jahra Governorate
  waha: {
    id: "waha",
    en: "Waha",
    ar: "الواحة",
    center: { lat: 29.337, lng: 47.658 },
  },
  qasr: {
    id: "qasr",
    en: "Qasr",
    ar: "القصر",
    center: { lat: 29.337, lng: 47.658 },
  },
  naeem: {
    id: "naeem",
    en: "Naeem",
    ar: "النعيم",
    center: { lat: 29.337, lng: 47.658 },
  },
  oyoun: {
    id: "oyoun",
    en: "Oyoun",
    ar: "العيون",
    center: { lat: 29.337, lng: 47.658 },
  },
  naseem: {
    id: "naseem",
    en: "Naseem",
    ar: "النسيم",
    center: { lat: 29.337, lng: 47.658 },
  },
  taima: {
    id: "taima",
    en: "Taima",
    ar: "تيماء",
    center: { lat: 29.337, lng: 47.658 },
  },
  saadAlAbdullahCity: {
    id: "saadAlAbdullahCity",
    en: "Saad Al-Abdullah City",
    ar: "مدينة سعد العبدالله",
    center: { lat: 29.337, lng: 47.658 },
  },
  mutlaa: {
    id: "mutlaa",
    en: "Mutlaa",
    ar: "المطالع",
    center: { lat: 29.337, lng: 47.658 },
  },
  jahraNew: {
    id: "jahraNew",
    en: "Jahra New",
    ar: "الجهراء الجديدة",
    center: { lat: 29.337, lng: 47.658 },
  },
  jahraOld: {
    id: "jahraOld",
    en: "Jahra Old",
    ar: "الجهراء القديمة",
    center: { lat: 29.337, lng: 47.658 },
  },
  jahraSouth: {
    id: "jahraSouth",
    en: "Jahra South",
    ar: "جنوب الجهراء",
    center: { lat: 29.337, lng: 47.658 },
  },
  amghara: {
    id: "amghara",
    en: "Amghara",
    ar: "أمغرة",
    center: { lat: 29.337, lng: 47.658 },
  },
  sulaibiya: {
    id: "sulaibiya",
    en: "Sulaibiya",
    ar: "الصليبية",
    center: { lat: 29.337, lng: 47.658 },
  },
  abdali: {
    id: "abdali",
    en: "Abdali",
    ar: "العبدلي",
    center: { lat: 29.337, lng: 47.658 },
  },
  rawdatain: {
    id: "rawdatain",
    en: "Rawdatain",
    ar: "الروضتين",
    center: { lat: 29.337, lng: 47.658 },
  },
  kabed: {
    id: "kabed",
    en: "Kabed",
    ar: "كبد",
    center: { lat: 29.337, lng: 47.658 },
  },
  salmi: {
    id: "salmi",
    en: "Salmi",
    ar: "السالمي",
    center: { lat: 29.337, lng: 47.658 },
  },
  subiya: {
    id: "subiya",
    en: "Subiya",
    ar: "الصبية",
    center: { lat: 29.337, lng: 47.658 },
  },
}
